platform :ios, '16.0'

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

use_expo_modules!
use_frameworks! :linkage => :static
use_react_native!(:path => config["reactNativePath"])

target 'Lavia' do
  use_expo_modules!
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'Firebase/Core'
  
  # GRPC-ni xüsusi versiyaya bağla
  pod 'gRPC-Core', '1.49.1'
  pod 'gRPC-C++', '1.49.1'
  pod 'BoringSSL-GRPC', '0.9.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      
      # BoringSSL-GRPC üçün xüsusi düzəliş
      if target.name == 'BoringSSL-GRPC'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'GRPC_DISABLE_CFSTREAM=1'
        config.build_settings['OTHER_CFLAGS'] = '$(inherited) -Wno-error=unused-command-line-argument'
      end
      
      # gRPC-Core üçün
      if target.name == 'gRPC-Core'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'GRPC_DISABLE_CFSTREAM=1'
      end
    end
  end
end